import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

class PdfService:
    def generate_trip_pdf(self, trip_data: dict, filename: str):
        """Generates a PDF itinerary in the background."""
        os.makedirs("generated_pdfs", exist_ok=True)
        filepath = f"generated_pdfs/{filename}.pdf"
        
        c = canvas.Canvas(filepath, pagesize=letter)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(100, 750, "TripMate Itinerary")
        
        c.setFont("Helvetica", 14)
        c.drawString(100, 710, f"Trip Title: {trip_data['title']}")
        c.drawString(100, 690, f"Start Date: {trip_data['start_date']}")
        c.drawString(100, 670, f"End Date: {trip_data['end_date']}")
        c.drawString(100, 650, f"Budget: ${trip_data['budget']}")
        c.drawString(100, 630, f"Status: {trip_data['status']}")
        
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(100, 600, "Generated by TripMate AI")
        c.save()
        print(f"PDF Generated successfully at {filepath}")
