"""add phone and dob to user

Revision ID: a807d0e2108e
Revises: 316aff8ba33b
Create Date: 2026-08-06 07:07:14.809645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a807d0e2108e'
down_revision: Union[str, Sequence[str], None] = '316aff8ba33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
